replicaCount: 1

image:
  repository: yolopython/user-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP # Use LoadBalancer for GKE
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  path: /ping
